import Head from 'next/head';
import React from 'react';
import Home1 from '../components/Home1';

export default function Home() {

	return (
		<div>
			<Head>
				<title>Staking Contract</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className='container w-600 mt-32'>
        <Home1 />
			</main>
		</div>
	);
}
